=== ImLionelGitz/Website/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Generated Schema",
  "description": "Generated from JSON data",
  "type": "object",
  "properties": {
    "home": {
      "type": "object",
      "properties": {
        "reviews": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "comments": {
                "type": "string"
              },
              "pfp": {
                "type": "string",
                "format": "uri"
              },
              "ratings": {
                "type": "integer"
              }
            },
            "required": [
              "comments",
              "name",
              "pfp",
              "ratings"
            ]
          },
          "minItems": 0
        },
        "news": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "title": {
                "type": "string"
              },
              "summry": {
                "type": "string"
              },
              "author": {
                "type": "string"
              },
              "uploadDate": {
                "type": "string"
              },
              "link": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "author",
              "link",
              "summry",
              "title",
              "uploadDate"
            ]
          },
          "minItems": 0
        }
      },
      "required": [
        "news",
        "reviews"
      ]
    },
    "apps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "img": {
            "type": "string",
            "format": "uri"
          },
          "platforms": {
            "type": "object",
            "properties": {
              "android": {
                "type": "string",
                "format": "uri"
              },
              "windows": {
                "type": "string",
                "format": "uri"
              },
              "universal": {
                "type": "string",
                "format": "uri"
              },
              "multiplayer": {
                "type": "string",
                "format": "uri"
              }
            }
          },
          "category": {
            "type": "string"
          },
          "genre": {
            "type": "string"
          },
          "mode": {
            "type": "string"
          }
        },
        "required": [
          "category",
          "genre",
          "img",
          "mode",
          "name",
          "platforms"
        ]
      },
      "minItems": 0
    },
    "videos": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "urlID": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "uploadDate": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "genre": {
            "type": "string"
          }
        },
        "required": [
          "category",
          "genre",
          "title",
          "uploadDate",
          "urlID"
        ]
      },
      "minItems": 0
    },
    "portfolio": {
      "type": "object",
      "properties": {
        "media": {
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string",
                  "format": "uri"
                },
                "content": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "price": {
                        "type": "integer"
                      },
                      "views": {
                        "type": "integer"
                      },
                      "remarks": {
                        "type": "string"
                      },
                      "isVideo": {
                        "type": "boolean"
                      },
                      "url": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "isVideo",
                      "price",
                      "remarks",
                      "url",
                      "views"
                    ],
                    "if": {
                      "properties": {
                        "isVideo": {
                          "const": false
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "url": {
                          "type": "string",
                          "pattern": "^https?://"
                        }
                      }
                    }
                  },
                  "minItems": 0
                }
              },
              "required": [
                "content",
                "icon"
              ]
            }
          }
        },
        "apps": {
          "type": "object",
          "properties": {
            "^.*$": {
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string"
                },
                "content": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "platforms": {
                        "type": "array",
                        "items": {}
                      },
                      "remarks": {
                        "type": "string"
                      },
                      "url": {
                        "type": "string",
                        "format": "uri"
                      }
                    },
                    "required": [
                      "platforms",
                      "remarks",
                      "url"
                    ]
                  },
                  "minItems": 0
                }
              },
              "required": [
                "content",
                "icon"
              ]
            }
          }
        },
        "models": {
          "type": "object",
          "properties": {
            "^.*$": {
              "type": "object",
              "properties": {
                "icon": {
                  "type": "string"
                },
                "content": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": [
                "content",
                "icon"
              ]
            }
          }
        }
      },
      "required": [
        "apps",
        "media",
        "models"
      ]
    }
  },
  "required": [
    "apps",
    "home",
    "portfolio",
    "videos"
  ]
}

=== ImLionelGitz/Website/public/Test2.json
{
    "$schema": "../schema.json",

    "home": {
        "reviews": [
            {
                "name": "lol",
                "comments": "The quick brown fox jumps over the lazy dog",
                "pfp": "/pfp1.jpg",
                "ratings": 0
            },
            {
                "name": "lol",
                "comments": "The quick brown fox jumps over the lazy dog",
                "pfp": "/pfp1.jpg",
                "ratings": 0
            },
            {
                "name": "lol",
                "comments": "The quick brown fox jumps over the lazy dog",
                "pfp": "/pfp1.jpg",
                "ratings": 0
            }
        ],
        "news": [
            {
                "title": "Buu Died",
                "summry": "kokokokkokokoko",
                "author": "Me",
                "uploadDate": "12/02/2000",
                "link": "#"
            },
            {
                "title": "Buu Died",
                "summry": "kokokokkokokoko",
                "author": "Me",
                "uploadDate": "12/02/2000",
                "link": "#"
            }
        ]
    },
    "apps": [
        {
            "name": "Learn Python",
            "img": "https://play-lh.googleusercontent.com/yzjoC50KOfHh5pvp71rXYPhjduQS5HTH7C0WcAbz8gIbHtEAF1tkeNt6B3e4QXykAHU=w480-h960-rw",
            "platforms": {
                "android": "#"
            },
            "category": "utility",
            "genre": "roleplay",
            "mode": "single"
        },
        {
            "name": "Shadow Fight",
            "img": "https://play-lh.googleusercontent.com/mNbe4RCs92XXpSmrheXWLs4Dl9OO6NcVdneyYSGKupzmjPo8-5wm51mS-uli5ylWWgt1",
            "platforms": {
                "android": ""
            },
            "category": "game",
            "genre": "fight",
            "mode": "multi"
        },
        {
            "name": "Criminal Case",
            "img": "https://play-lh.googleusercontent.com/v-eKNuoW4aUxQAFnztQICchU5OihGdsV2Za0y9WdsGo7e7zpl5Xg_rYqxcFHeuVdeLPW",
            "platforms": {},
            "category": "game",
            "genre": "roleplay",
            "mode": "multi"
        }
    ],
    "videos": [
        {
            "urlID": "1WF1Dx_OBYs",
            "title": "Buu Died",
            "uploadDate": "12/02/2000",
            "category": "game",
            "genre": "fight"
        },
        {
            "urlID": "Dq4Kx51S-WM",
            "title": "Buu Died",
            "uploadDate": "12/02/2002",
            "category": "bedwars",
            "genre": "boxing"
        }
    ],
    "portfolio": {
        "media": {
            "goku": {
                "icon": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGNRWnSbtAzcB9_rouhPBIX6vnTvE65a5JHA&s",
                "content": [
                    {
                        "price": 100,
                        "views": 200,
                        "remarks": "ha ha ha ha",
                        "isVideo": false,
                        "url": "https://img2.wallspic.com/crops/9/2/1/2/7/172129/172129-anime-dragon_ball_super-goku-zamasu-dragon_ball-2560x1440.jpg"
                    },
                    {
                        "price": 100,
                        "views": 200,
                        "remarks": "ha ha ha ha",
                        "isVideo": false,
                        "url": "https://img1.wallspic.com/previews/9/6/9/4/6/164969/164969-goku-dragon_ball_super_broly-superman-broly-superhero-x750.jpg"
                    },
                    {
                        "price": 100,
                        "views": 200,
                        "remarks": "ha ha ha ha",
                        "isVideo": true,
                        "url": "1WF1Dx_OBYs"
                    }
                ]
            }
        },
        "apps": {
            "unity": {
                "icon": "/unity.png",
                "content": [
                    {
                        "platforms": [],
                        "remarks": "ha ha ha ha",
                        "url": "https://img2.wallspic.com/crops/9/2/1/2/7/172129/172129-anime-dragon_ball_super-goku-zamasu-dragon_ball-2560x1440.jpg"
                    }
                ]
            }
        },
        "models": {
            "jamal": {
                "icon": "/cell.png",
                "content": "https://sketchfab.com/3d-models/udin-din-din-dun-madin-din-din-dun-game-model-4d90fef723fd4b18aea3ab253c013eb9"
            }
        }
    }
}
